### ISSUE TITLE
custom RNAseq data

### ISSUE THREAD

**Issue by lalalagartija** [cmdoret/Acastellanii_genome_annotation#2]
Hi, 
Is it possible to run your pipeline with funannotate installed with docker rather than conda ? 
Second question : is it possible to add custom rnaseq data in addition to yours ? 

Thank you very much,

**Comment by cmdoret** [comment]
Hi @lalalagartija 

It should be possible to use docker, either by specifying individual images using[ Snakemake's `container` directive](https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#running-jobs-in-containers) or using [the new --containerize feature](https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#containerization-of-conda-based-workflows) (I've never tried it.) So in brief, yes but some changes are needed. I just added a license, so you're welcome to fork or even make a PR if you feel like it.

It should be possible to use custom RNAseq data by changing the SRA identifiers in the [units.tsv](https://github.com/cmdoret/Acastellanii_genome_annotation/blob/master/units.tsv) file. I've not tried it, so there may be unexpected behaviours.

**Comment by lalalagartija** [comment]
Great thanks, I will let you know if I manage. 

another question : are your annotations of your assembly GCA_021020605.1 available somewhere without having to run the pipeline ?

**Comment by cmdoret** [comment]
You can find the assembly and corresponding annotations used in the paper in the associated Zenodo record.

I seem to remember the assembly on NCBI is an improved version that was submitted by our canadian colleagues. I will put you in touch.
